# Generated by Django 3.0.6 on 2020-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=30)),
                ('user_position', models.TextField(max_length=200)),
                ('user_company', models.TextField(max_length=30)),
                ('user_description', models.TextField(max_length=500)),
                ('job_title', models.TextField()),
            ],
        ),
    ]
